# Site settings
name: James Xu Blog
email: 15695713696@163.com
author: James Xu
github: https://github.com/luoyan35714/
baseurl: ""

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xushuguang

# Build settings
markdown: kramdown

